### ISSUE TITLE
Tests crashed when running CI on forks

### ISSUE THREAD

**Issue by gomzyakov** [avtocod/svdb-jdbc-driver#11]
@eldario @stepangek 

Example: https://github.com/gomzyakov/svdb-jdbc-driver/actions/runs/10824671841

**Comment by stepangek** [comment]
Now this situation is fixed.

**Comment by gomzyakov** [comment]
Yep, all fine https://github.com/gomzyakov/svdb-jdbc-driver/actions/runs/10844391219/job/30093171573

Thanks for the response!
